import { QualitiesType } from "../types";

export const quals: QualitiesType[] = [
  {
    color: "BEIGE",
    qualityGroup: "BEIGE TRAVERTINO",
    count: 6,
    imageName: "NULL",
  },
  {
    color: "BEIGE",
    qualityGroup: "BURBERRY BEIGE",
    count: 19,
    imageName: "LE01345",
  },
  {
    color: "BEIGE",
    qualityGroup: "CAPUCCHINO",
    count: 12,
    imageName: "LL00356",
  },
  {
    color: "BEIGE",
    qualityGroup: "CREMA BELLESIMO",
    count: 2,
    imageName: "LH60176",
  },
  {
    color: "BEIGE",
    qualityGroup: "CREMA UNIQUE",
    count: 2,
    imageName: "LM00271",
  },
  {
    color: "BEIGE",
    qualityGroup: "FANTASY CLARA",
    count: 8,
    imageName: "LM02825",
  },
  {
    color: "BEIGE",
    qualityGroup: "KASTAMANU BEIGE",
    count: 4,
    imageName: "LN02022",
  },
  {
    color: "BEIGE",
    qualityGroup: "NOVANA BEIGE",
    count: 15,
    imageName: "LJ02029",
  },
  {
    color: "BEIGE",
    qualityGroup: "REGAL BEIGE",
    count: 29,
    imageName: "LL02273",
  },
  {
    color: "BEIGE",
    qualityGroup: "ROSSO ATLANTIDE",
    count: 8,
    imageName: "LM01229",
  },
  {
    color: "BLACK",
    qualityGroup: "BLACK MARQUINA",
    count: 2,
    imageName: "11KM027",
  },
  {
    color: "BLACK",
    qualityGroup: "BLACK WAVE",
    count: 35,
    imageName: "11KL114",
  },
  {
    color: "BLACK",
    qualityGroup: "GOLDEN PORTORO",
    count: 6,
    imageName: "LE60271",
  },
  {
    color: "BLACK",
    qualityGroup: "METTALLIC BRONZE",
    count: 12,
    imageName: "LL03127",
  },
  {
    color: "BLACK",
    qualityGroup: "NERO ANTIQUE",
    count: 4,
    imageName: "11KN251",
  },
  {
    color: "BLACK",
    qualityGroup: "NERO FOSSILE",
    count: 2,
    imageName: "10K0BH28",
  },
  {
    color: "BLACK",
    qualityGroup: "SAINT LAURENT",
    count: 7,
    imageName: "LK01483",
  },
  {
    color: "BLACK",
    qualityGroup: "SILVER DRAGON",
    count: 1,
    imageName: "11KO013",
  },
  {
    color: "BROWN",
    qualityGroup: "BRONZE ARMANI",
    count: 15,
    imageName: "11KI159",
  },
  {
    color: "BROWN",
    qualityGroup: "DARK EMPRADOR",
    count: 2,
    imageName: "MK00015B",
  },
  {
    color: "BROWN",
    qualityGroup: "GOLDEN EMPRESS",
    count: 1,
    imageName: "LL03190",
  },
  {
    color: "BROWN",
    qualityGroup: "METTALLIC BRONZE",
    count: 12,
    imageName: "LM02043A",
  },
  {
    color: "BROWN",
    qualityGroup: "NOIR ARMANI",
    count: 2,
    imageName: "LL00002",
  },
  {
    color: "BROWN",
    qualityGroup: "OLYMPIA BROWN",
    count: 3,
    imageName: "LM00992",
  },
  {
    color: "BROWN",
    qualityGroup: "PETRA FUSION",
    count: 3,
    imageName: "LM01139A",
  },
  {
    color: "EXOTIC",
    qualityGroup: "ALPINE WHITE",
    count: 2,
    imageName: "11PO057",
  },
  {
    color: "EXOTIC",
    qualityGroup: "AMAZONITE",
    count: 23,
    imageName: "11PJ042",
  },
  {
    color: "EXOTIC",
    qualityGroup: "AMYTIESTA",
    count: 2,
    imageName: "21PE0004",
  },
  {
    color: "EXOTIC",
    qualityGroup: "ANTIGUA",
    count: 1,
    imageName: "11PM004",
  },
  {
    color: "EXOTIC",
    qualityGroup: "AVOCATUS",
    count: 4,
    imageName: "11PN062",
  },
  {
    color: "EXOTIC",
    qualityGroup: "AZUL MACAUBAS",
    count: 6,
    imageName: "11PN096",
  },
  {
    color: "EXOTIC",
    qualityGroup: "BAOBAB",
    count: 13,
    imageName: "11PK010",
  },
  {
    color: "EXOTIC",
    qualityGroup: "BLUE AZUL",
    count: 15,
    imageName: "11PL057",
  },
  {
    color: "EXOTIC",
    qualityGroup: "BLUE BAHIYA",
    count: 15,
    imageName: "11PN082",
  },
  {
    color: "EXOTIC",
    qualityGroup: "BLUE CALCITE",
    count: 6,
    imageName: "11KN070",
  },
  {
    color: "EXOTIC",
    qualityGroup: "BLUE ROMA",
    count: 65,
    imageName: "11PI025",
  },
  {
    color: "EXOTIC",
    qualityGroup: "BLUE VELVET",
    count: 1,
    imageName: "11PN045",
  },
  {
    color: "EXOTIC",
    qualityGroup: "BOTANIC CRYSTAL",
    count: 3,
    imageName: "11PK023",
  },
  {
    color: "EXOTIC",
    qualityGroup: "BOTANIC WAVE",
    count: 16,
    imageName: "11PL082",
  },
  {
    color: "EXOTIC",
    qualityGroup: "BRAMANT MAESTRO",
    count: 1,
    imageName: "11PM076",
  },
  {
    color: "EXOTIC",
    qualityGroup: "CEPPO",
    count: 6,
    imageName: "11KN147",
  },
  {
    color: "EXOTIC",
    qualityGroup: "CIPOLLINO VERDE",
    count: 8,
    imageName: "11KN229",
  },
  {
    color: "EXOTIC",
    qualityGroup: "COLIBRI BLUE",
    count: 2,
    imageName: "11PN091",
  },
  {
    color: "EXOTIC",
    qualityGroup: "COPACABANA",
    count: 6,
    imageName: "11PN023",
  },
  {
    color: "EXOTIC",
    qualityGroup: "COSMOPOLITAN",
    count: 5,
    imageName: "11PN061",
  },
  {
    color: "EXOTIC",
    qualityGroup: "DIASPRO",
    count: 15,
    imageName: "11KJ051",
  },
  {
    color: "EXOTIC",
    qualityGroup: "EBANO QUARTZITE",
    count: 1,
    imageName: "11PO040",
  },
  {
    color: "EXOTIC",
    qualityGroup: "FUSION WOW",
    count: 2,
    imageName: "11PL076",
  },
  {
    color: "EXOTIC",
    qualityGroup: "GOLDEN JAZZ",
    count: 4,
    imageName: "11PN016",
  },
  {
    color: "EXOTIC",
    qualityGroup: "GOLDEN PINEATA",
    count: 1,
    imageName: "LL02888",
  },
  {
    color: "EXOTIC",
    qualityGroup: "GRAN ANTIQUE",
    count: 3,
    imageName: "11KJ227",
  },
  {
    color: "EXOTIC",
    qualityGroup: "GREEN LAVANTE",
    count: 1,
    imageName: "LM01222",
  },
  {
    color: "EXOTIC",
    qualityGroup: "ICEBERG",
    count: 48,
    imageName: "11KK039",
  },
  {
    color: "EXOTIC",
    qualityGroup: "INFINITY",
    count: 1,
    imageName: "Q110009",
  },
  {
    color: "EXOTIC",
    qualityGroup: "IRISH GREEN",
    count: 3,
    imageName: "11KN145",
  },
  {
    color: "EXOTIC",
    qualityGroup: "MACAUBAS FANTASY",
    count: 1,
    imageName: "11PO020",
  },
  {
    color: "EXOTIC",
    qualityGroup: "MADERO",
    count: 11,
    imageName: "11PO016",
  },
  {
    color: "EXOTIC",
    qualityGroup: "MATRIX",
    count: 28,
    imageName: "10XE001",
  },
  {
    color: "EXOTIC",
    qualityGroup: "MOLDAVITE",
    count: 2,
    imageName: "11PN093",
  },
  {
    color: "EXOTIC",
    qualityGroup: "MOSCHINO",
    count: 4,
    imageName: "11PL012",
  },
  {
    color: "EXOTIC",
    qualityGroup: "NATURA",
    count: 2,
    imageName: "11PN077",
  },
  {
    color: "EXOTIC",
    qualityGroup: "OCEAN BLUE",
    count: 1,
    imageName: "11PO012",
  },
  {
    color: "EXOTIC",
    qualityGroup: "OREO QUARTZ",
    count: 15,
    imageName: "11PL043",
  },
  {
    color: "EXOTIC",
    qualityGroup: "PALLISANDRO",
    count: 1,
    imageName: "LK00828",
  },
  {
    color: "EXOTIC",
    qualityGroup: "PANTAGONIA",
    count: 32,
    imageName: "11PJ012",
  },
  {
    color: "EXOTIC",
    qualityGroup: "PATAGONIA VITTRO",
    count: 10,
    imageName: "11PM035",
  },
  {
    color: "EXOTIC",
    qualityGroup: "PENTAGONIA",
    count: 2,
    imageName: "11PO010",
  },
  {
    color: "EXOTIC",
    qualityGroup: "PHANTOM BLACK",
    count: 5,
    imageName: "11PI037",
  },
  {
    color: "EXOTIC",
    qualityGroup: "PINK PATAGONIA",
    count: 2,
    imageName: "11PM079",
  },
  {
    color: "EXOTIC",
    qualityGroup: "QUARZO ROSA",
    count: 6,
    imageName: "11PL087",
  },
  {
    color: "EXOTIC",
    qualityGroup: "RED MALIBU",
    count: 7,
    imageName: "11PP010",
  },
  {
    color: "EXOTIC",
    qualityGroup: "ROSSO LAVANTE",
    count: 1,
    imageName: "LN01982A",
  },
  {
    color: "EXOTIC",
    qualityGroup: "ROSSO LUNA",
    count: 1,
    imageName: "11KM216",
  },
  {
    color: "EXOTIC",
    qualityGroup: "SODALITE BLUE",
    count: 6,
    imageName: "11PJ027",
  },
  {
    color: "EXOTIC",
    qualityGroup: "SUPER WHITE",
    count: 2,
    imageName: "11KL038",
  },
  {
    color: "EXOTIC",
    qualityGroup: "TAJMAHAL",
    count: 5,
    imageName: "11PN022",
  },
  {
    color: "EXOTIC",
    qualityGroup: "TITANIUM GOLD",
    count: 2,
    imageName: "11KN077",
  },
  {
    color: "EXOTIC",
    qualityGroup: "TURTLE SHELL",
    count: 7,
    imageName: "21PF0003",
  },
  {
    color: "EXOTIC",
    qualityGroup: "TWILIGHT GREEN",
    count: 1,
    imageName: "11KN065",
  },
  {
    color: "EXOTIC",
    qualityGroup: "VERDE FOREST",
    count: 6,
    imageName: "11KN114",
  },
  {
    color: "EXOTIC",
    qualityGroup: "VERDE GREEN",
    count: 2,
    imageName: "11PM019",
  },
  {
    color: "GREY",
    qualityGroup: "ABSTRACT GREY",
    count: 1,
    imageName: "LM02222",
  },
  {
    color: "GREY",
    qualityGroup: "AMAZING GREY",
    count: 33,
    imageName: "LK00729",
  },
  {
    color: "GREY",
    qualityGroup: "BRUNELI GREY",
    count: 1,
    imageName: "11KM156",
  },
  {
    color: "GREY",
    qualityGroup: "CAPUCCHINO",
    count: 12,
    imageName: "NULL",
  },
  {
    color: "GREY",
    qualityGroup: "CEPPO",
    count: 6,
    imageName: "LN00639",
  },
  {
    color: "GREY",
    qualityGroup: "CLOUD GREY",
    count: 3,
    imageName: "LN02284",
  },
  {
    color: "GREY",
    qualityGroup: "GOLDEN PINEATA",
    count: 1,
    imageName: "LL02887",
  },
  {
    color: "GREY",
    qualityGroup: "GREY DIASPRO",
    count: 3,
    imageName: "11KM136",
  },
  {
    color: "GREY",
    qualityGroup: "GRIGO ARMANI",
    count: 24,
    imageName: "LM01625",
  },
  {
    color: "GREY",
    qualityGroup: "KOH GREY",
    count: 16,
    imageName: "LJ02326",
  },
  {
    color: "GREY",
    qualityGroup: "MOUNTAIN BLUE",
    count: 1,
    imageName: "LP00329",
  },
  {
    color: "GREY",
    qualityGroup: "PALLISANDRO",
    count: 1,
    imageName: "11KI207",
  },
  {
    color: "GREY",
    qualityGroup: "PIETRA GREY",
    count: 4,
    imageName: "LM03295",
  },
  {
    color: "GREY",
    qualityGroup: "SANATA GREY",
    count: 11,
    imageName: "LJ01663",
  },
  {
    color: "GREY",
    qualityGroup: "SUPER WHITE",
    count: 2,
    imageName: "11KK098",
  },
  {
    color: "GREY",
    qualityGroup: "TITANIUM",
    count: 1,
    imageName: "LO03006A",
  },
  {
    color: "GREY",
    qualityGroup: "TUNDRA GREY",
    count: 4,
    imageName: "LM00383",
  },
  {
    color: "GREY",
    qualityGroup: "VERSACE GOLD",
    count: 4,
    imageName: "LL02553A",
  },
  {
    color: "MULTI-COLOR",
    qualityGroup: "INFINITY",
    count: 1,
    imageName: "Q110009A",
  },
  {
    color: "MULTI-COLOR",
    qualityGroup: "ROSSO LAVANTE",
    count: 1,
    imageName: "LM00363",
  },
  {
    color: "MULTICOLOUR",
    qualityGroup: "PALLISANDRO",
    count: 1,
    imageName: "NM00006",
  },
  {
    color: "MULTICOLOUR",
    qualityGroup: "RED ALICANTE",
    count: 2,
    imageName: "MK00018",
  },
  {
    color: "MULTICOLOUR",
    qualityGroup: "RED FUSION",
    count: 2,
    imageName: "11PO047",
  },
  {
    color: "ONYX",
    qualityGroup: "BLUE ONYX",
    count: 1,
    imageName: "11KJ014",
  },
  {
    color: "ONYX",
    qualityGroup: "CRYSTAL ONYX",
    count: 11,
    imageName: "11KL258",
  },
  {
    color: "ONYX",
    qualityGroup: "GREEN ONYX",
    count: 4,
    imageName: "10K3451",
  },
  {
    color: "ONYX",
    qualityGroup: "GREEN PARADISO ONYX",
    count: 1,
    imageName: "LM00379",
  },
  {
    color: "ONYX",
    qualityGroup: "GREY ONYX",
    count: 3,
    imageName: "11KJ020",
  },
  {
    color: "ONYX",
    qualityGroup: "MEXICAN ONYX",
    count: 4,
    imageName: "10K9226",
  },
  {
    color: "ONYX",
    qualityGroup: "ORANGE ONYX",
    count: 1,
    imageName: "11KN067",
  },
  {
    color: "ONYX",
    qualityGroup: "PINK ONYX",
    count: 6,
    imageName: "11KJ191",
  },
  {
    color: "ONYX",
    qualityGroup: "RAINBOW ONYX",
    count: 2,
    imageName: "11KI103",
  },
  {
    color: "ONYX",
    qualityGroup: "WHITE CRYSTAL",
    count: 2,
    imageName: "11KL270",
  },
  {
    color: "ONYX",
    qualityGroup: "WHITE ONYX",
    count: 4,
    imageName: "11KJ011",
  },
  {
    color: "TRAVERTINO",
    qualityGroup: "BEIGE TRAVERTINO",
    count: 6,
    imageName: "LD00810",
  },
  {
    color: "TRAVERTINO",
    qualityGroup: "EBONY TRAVERTINO",
    count: 2,
    imageName: "LL00913",
  },
  {
    color: "TRAVERTINO",
    qualityGroup: "MARINA TRAVERTINO",
    count: 1,
    imageName: "11KL222",
  },
  {
    color: "TRAVERTINO",
    qualityGroup: "RED TRAVERTINO",
    count: 6,
    imageName: "LM03287",
  },
  {
    color: "TRAVERTINO",
    qualityGroup: "SILVER TRAVERTINO",
    count: 3,
    imageName: "LI00853",
  },
  {
    color: "TRAVERTINO",
    qualityGroup: "TITANIUM",
    count: 1,
    imageName: "LI02078",
  },
  {
    color: "WHITE",
    qualityGroup: "BIANCO CARRARA",
    count: 1,
    imageName: "11KL293",
  },
  {
    color: "WHITE",
    qualityGroup: "BIANCO LASA",
    count: 10,
    imageName: "11KN309",
  },
  {
    color: "WHITE",
    qualityGroup: "BIANCO ORO",
    count: 26,
    imageName: "11KL176",
  },
  {
    color: "WHITE",
    qualityGroup: "BIANCO SPIDER",
    count: 2,
    imageName: "LL00978",
  },
  {
    color: "WHITE",
    qualityGroup: "BIANCO VENATO",
    count: 9,
    imageName: "LG60411",
  },
  {
    color: "WHITE",
    qualityGroup: "CALACATTA",
    count: 1,
    imageName: "11KI209",
  },
  {
    color: "WHITE",
    qualityGroup: "CALACATTA BORGHINI",
    count: 7,
    imageName: "11KL348",
  },
  {
    color: "WHITE",
    qualityGroup: "CALACATTA MACCHIA VECCHIA",
    count: 6,
    imageName: "11KI205",
  },
  {
    color: "WHITE",
    qualityGroup: "CARRARA",
    count: 2,
    imageName: "11KI201",
  },
  {
    color: "WHITE",
    qualityGroup: "DOVER WHITE",
    count: 25,
    imageName: "LK01102B",
  },
  {
    color: "WHITE",
    qualityGroup: "INDIAN PANDA",
    count: 49,
    imageName: "LM02627",
  },
  {
    color: "WHITE",
    qualityGroup: "LILAC",
    count: 21,
    imageName: "LK01209",
  },
  {
    color: "WHITE",
    qualityGroup: "MICHAEL ANGELO",
    count: 1,
    imageName: "LL02369",
  },
  {
    color: "WHITE",
    qualityGroup: "MICHEAL ANGELO FIGARO",
    count: 6,
    imageName: "LL02885",
  },
  {
    color: "WHITE",
    qualityGroup: "MICHELANGELO",
    count: 19,
    imageName: "11KI127",
  },
  {
    color: "WHITE",
    qualityGroup: "ORIENTAL STATUARIO",
    count: 4,
    imageName: "11KM148",
  },
  {
    color: "WHITE",
    qualityGroup: "PANDA BLACK",
    count: 49,
    imageName: "11KL113",
  },
  {
    color: "WHITE",
    qualityGroup: "PANDA WHITE",
    count: 51,
    imageName: "11KL199",
  },
  {
    color: "WHITE",
    qualityGroup: "STATUARIO BRONZE",
    count: 2,
    imageName: "LL00717",
  },
  {
    color: "WHITE",
    qualityGroup: "STATUARIO CALACATTA",
    count: 2,
    imageName: "11KN110",
  },
  {
    color: "WHITE",
    qualityGroup: "STATUARIO COLORADO",
    count: 8,
    imageName: "LK00372",
  },
  {
    color: "WHITE",
    qualityGroup: "STATURIO",
    count: 10,
    imageName: "11KI108",
  },
  {
    color: "WHITE",
    qualityGroup: "SUPER WHITE",
    count: 2,
    imageName: "NULL",
  },
  {
    color: "WHITE",
    qualityGroup: "V GALAXY WHITE",
    count: 33,
    imageName: "LN00254",
  },
  {
    color: "WHITE",
    qualityGroup: "VOLAKAS",
    count: 45,
    imageName: "LL01240",
  },
  {
    color: "WHITE",
    qualityGroup: "YELLOW FERN",
    count: 1,
    imageName: "LN02307",
  },
];
